name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    name: Run Test Suite
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      run: |
        cd src
        python -m pytest ../tests/ -v
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/

  train-and-quantize:
    runs-on: ubuntu-latest
    name: Train Model and Quantize
    needs: test-suite
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        cd src
        python train.py
    
    - name: Run quantization
      run: |
        cd src
        python quantize.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: |
          src/*.joblib
          *.joblib

  build-and-test-container:
    runs-on: ubuntu-latest
    name: Build and Test Docker Container
    needs: train-and-quantize
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download model artifacts
      uses: actions/download-artifact@v3
      with:
        name: model-artifacts
        path: ./
    
    - name: Build Docker image
      run: |
        docker build -t mlops-pipeline .
    
    - name: Test Docker container
      run: |
        docker run --rm mlops-pipeline
    
    - name: Test predict.py execution
      run: |
        docker run --rm mlops-pipeline python src/predict.py